#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────
#
# First production deploy of Nouveau to artful-chameleon-402. Run from the
# repo root:
#
#   bash scripts/deploy-prod.sh
#
# Every command that touches prod is gated behind a confirm. Non-secret
# values (GCP project id, Google client id) are remembered in a gitignored
# .env.prod.local so a re-run can skip ahead; secrets are never written to
# disk by this script.

TOTAL_STAGES=8

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BACKEND_DIR="$REPO_ROOT/packages/backend"
ENV_FILE="$BACKEND_DIR/.env.prod.local"

PROD_DEPLOYMENT="prod:artful-chameleon-402"
PROD_SITE_URL="https://artful-chameleon-402.convex.site"
PROD_REDIRECT_URI="$PROD_SITE_URL/oauth/google/callback"
PROD_AGENTMAIL_WEBHOOK="$PROD_SITE_URL/api/agentmail/webhook"

# prod_env set|get KEY [VALUE]: runs the Convex env command against prod.
# Runs from packages/backend so the CLI finds the project; the explicit
# CONVEX_DEPLOYMENT override is what steers it to prod (same pattern as
# `bun run deploy`).
prod_env() {
  (cd "$BACKEND_DIR" && CONVEX_DEPLOYMENT="$PROD_DEPLOYMENT" npx convex env "$@")
}
# dev_env_get KEY: reads a value off the dev deployment named in .env.local.
dev_env_get() {
  (cd "$BACKEND_DIR" && npx convex env get "$1" 2>/dev/null | tail -n1) || true
}
# announce: the deploy-guard line, printed before every prod-affecting stage.
announce() { warn "target: prod (artful-chameleon-402) — $1"; }

cd "$REPO_ROOT"

banner "Nouveau: first prod deploy (artful-chameleon-402)"

# ── Stage 1: prod Google OAuth client ─────────────────────────────────────
stage "Google Cloud: prod OAuth client"
say "Dev and prod need separate OAuth clients because each has its own"
say "callback URL. Reuse the dev GCP project; only the client is new."
ask GCP_PROJECT_ID "GCP project id (the one holding the dev OAuth client):"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
open_url "https://console.cloud.google.com/auth/clients/create?project=$GCP_PROJECT_ID"
step "Application type: Web application."
step "Name: Nouveau prod."
step "Under Authorized redirect URIs, add exactly:"
note "    $PROD_REDIRECT_URI"
say "Authorized JavaScript origins are not needed."
step "Create, then copy the client ID and the client secret."
ask GOOGLE_CLIENT_ID "Paste the prod client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the prod client secret (hidden):"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
printf '\n'
say "Judges and anyone else must be able to sign in, so the consent screen"
say "cannot stay in Testing mode (test users only)."
open_url "https://console.cloud.google.com/auth/audience?project=$GCP_PROJECT_ID"
step "Under Publishing status, click 'Publish app' and confirm."
note "Email + profile scopes need no Google verification; users see a plain"
note "consent screen naming ${PROD_SITE_URL#https://} until a custom domain exists."
pause "Published? Press Enter to continue."

# ── Stage 2: copy shared sponsor keys dev -> prod ─────────────────────────
stage "Copy sponsor keys from dev to prod"
say "These four are per-account, not per-deployment, so the dev values are"
say "reused as-is: FIRECRAWL_API_KEY, FIRECRAWL_WEBHOOK_SECRET, OPENAI_API_KEY,"
say "AGENTMAIL_API_KEY (the broad key with inbox_create)."
announce "will set 4 env vars"
if confirm "Copy the four keys from dev (cool-giraffe-632) to prod now?"; then
  for key in FIRECRAWL_API_KEY FIRECRAWL_WEBHOOK_SECRET OPENAI_API_KEY AGENTMAIL_API_KEY; do
    value=$(dev_env_get "$key")
    if [[ -z "$value" ]]; then
      warn "$key is empty on dev; skipping"
      SKIPPED+=("prod env $key")
      continue
    fi
    prod_env set "$key" "$value"
    printf '  %s✓ set%s %s on prod\n' "$GREEN" "$RESET" "$key"
  done
else
  SKIPPED+=("prod env FIRECRAWL_API_KEY FIRECRAWL_WEBHOOK_SECRET OPENAI_API_KEY AGENTMAIL_API_KEY")
fi

# ── Stage 3: prod auth signing keys ───────────────────────────────────────
stage "Generate prod auth signing keys"
say "Convex Auth signs sessions with an RS256 key pair (AUTH_PRIVATE_KEY +"
say "AUTH_JWKS). Prod gets its own pair; dev's is never reused. Generated"
say "the same way the @convex-dev/auth CLI does it, in memory only."
announce "will set AUTH_PRIVATE_KEY and AUTH_JWKS"
existing_jwks=$(prod_env get AUTH_JWKS 2>/dev/null | tail -n1 || true)
if [[ -n "$existing_jwks" ]]; then
  warn "AUTH_JWKS is already set on prod; leaving both keys unchanged."
elif confirm "Generate a fresh key pair and set it on prod now?"; then
  keys_json=$(cd "$BACKEND_DIR" && node --input-type=module -e '
    import { generateKeyPair, exportPKCS8, exportJWK } from "jose";
    import { randomUUID } from "node:crypto";
    const ALG = "RS256";
    const { publicKey, privateKey } = await generateKeyPair(ALG, { extractable: true });
    const privatePem = await exportPKCS8(privateKey);
    const pubJwk = await exportJWK(publicKey);
    const jwks = JSON.stringify({ keys: [{ ...pubJwk, kid: randomUUID(), alg: ALG, use: "sig" }] });
    process.stdout.write(JSON.stringify({ privateKey: Buffer.from(privatePem).toString("base64"), jwks }));
  ')
  auth_private_key=$(printf '%s' "$keys_json" | node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(0,"utf8")).privateKey)')
  auth_jwks=$(printf '%s' "$keys_json" | node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(0,"utf8")).jwks)')
  prod_env set AUTH_PRIVATE_KEY "$auth_private_key"
  prod_env set AUTH_JWKS "$auth_jwks"
  printf '  %s✓ set%s AUTH_PRIVATE_KEY and AUTH_JWKS on prod\n' "$GREEN" "$RESET"
else
  SKIPPED+=("prod env AUTH_PRIVATE_KEY / AUTH_JWKS")
fi

# ── Stage 4: Google creds + SITE_URL on prod ──────────────────────────────
stage "Set Google credentials and SITE_URL on prod"
say "SITE_URL is the browsed origin the OAuth flow may redirect back to."
say "On prod the app is served by static hosting at the deployment's own"
say "site URL, so: $PROD_SITE_URL"
announce "will set AUTH_GOOGLE_CLIENT_ID, AUTH_GOOGLE_CLIENT_SECRET, SITE_URL"
if [[ -z "$GOOGLE_CLIENT_ID" || -z "$GOOGLE_CLIENT_SECRET" ]]; then
  warn "Google client id/secret missing (stage 1); skipping."
  SKIPPED+=("prod env AUTH_GOOGLE_CLIENT_ID / AUTH_GOOGLE_CLIENT_SECRET / SITE_URL")
elif confirm "Set the three values on prod now?"; then
  prod_env set AUTH_GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  prod_env set AUTH_GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
  prod_env set SITE_URL "$PROD_SITE_URL"
  printf '  %s✓ set%s Google creds + SITE_URL on prod\n' "$GREEN" "$RESET"
else
  SKIPPED+=("prod env AUTH_GOOGLE_CLIENT_ID / AUTH_GOOGLE_CLIENT_SECRET / SITE_URL")
fi

# ── Stage 5: deploy ───────────────────────────────────────────────────────
stage "Deploy backend + web to prod"
say "bun run deploy builds apps/web (reading apps/web/.env.production for the"
say "prod VITE_CONVEX_URL), pushes the Convex functions, and uploads the"
say "static bundle to the static-hosting component."
if [[ ! -f "$REPO_ROOT/apps/web/.env.production" ]]; then
  warn "apps/web/.env.production is missing; the web build would point at dev."
  SKIPPED+=("bun run deploy (create apps/web/.env.production first)")
else
  note "apps/web/.env.production -> $(cat "$REPO_ROOT/apps/web/.env.production")"
  announce "will push functions + schema + static site"
  if confirm "Run bun run deploy now?"; then
    bun run deploy
    printf '  %s✓ deployed%s to %s\n' "$GREEN" "$RESET" "$PROD_SITE_URL"
  else
    SKIPPED+=("bun run deploy")
  fi
fi

# ── Stage 6: seed roasters ────────────────────────────────────────────────
stage "Seed the curated roasters on prod"
say "seed:seedCuratedRoasters inserts the 20 curated roasters + crawlSources"
say "rows as pending. Idempotent. The crawl cron then takes the baseline"
say "(no alerts) and flips each roaster to active; alerts start at crawl #2."
announce "will insert up to 20 roasters + 20 crawlSources"
if confirm "Run the seed on prod now?"; then
  (cd "$BACKEND_DIR" && CONVEX_DEPLOYMENT="$PROD_DEPLOYMENT" npx convex run seed:seedCuratedRoasters '{}')
  printf '  %s✓ seeded%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("npx convex run seed:seedCuratedRoasters on prod")
fi

# ── Stage 7: AgentMail webhook ────────────────────────────────────────────
stage "AgentMail: prod delivery webhook"
say "The alert ledger learns sent/delivered/failed from AgentMail's Svix"
say "webhook. Webhook secrets are per endpoint, so prod needs its own."
open_url "https://console.agentmail.to"
step "Open Webhooks and add a new endpoint with this URL:"
note "    $PROD_AGENTMAIL_WEBHOOK"
step "Subscribe to the same event types as the dev endpoint"
note "    (the cool-giraffe-632.convex.site one; message delivery lifecycle)."
step "Save, then copy the endpoint's signing secret (starts whsec_)."
ask_secret AGENTMAIL_WEBHOOK_SECRET "Paste the prod webhook secret (hidden):"
if [[ -z "$AGENTMAIL_WEBHOOK_SECRET" ]]; then
  warn "empty secret; skipping"
  SKIPPED+=("prod env AGENTMAIL_WEBHOOK_SECRET")
else
  announce "will set AGENTMAIL_WEBHOOK_SECRET"
  if confirm "Set AGENTMAIL_WEBHOOK_SECRET on prod now?"; then
    prod_env set AGENTMAIL_WEBHOOK_SECRET "$AGENTMAIL_WEBHOOK_SECRET"
    printf '  %s✓ set%s AGENTMAIL_WEBHOOK_SECRET on prod\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("prod env AGENTMAIL_WEBHOOK_SECRET")
  fi
fi

# ── Stage 8: verify ───────────────────────────────────────────────────────
stage "Verify"
say "Backend health from the CLI, then a real sign-in in the browser."
(cd "$BACKEND_DIR" && CONVEX_DEPLOYMENT="$PROD_DEPLOYMENT" npx convex run healthCheck:get '{}') || warn "health check failed; see output above"
printf '\n'
say "Current prod env var names (values hidden):"
prod_env list 2>/dev/null | sed 's/=.*/=<set>/' | sed 's/^/    /' || true
printf '\n'
open_url "$PROD_SITE_URL"
step "Sign in with Google. You should land back on the app signed in, and a"
step "users row plus an AgentMail inbox should appear on prod."
step "Watch a roaster. The baseline crawl runs on the cron; roasters flip"
step "pending -> active as it lands. Alerts begin at each roaster's 2nd crawl."
note "Unsigned POST to $PROD_AGENTMAIL_WEBHOOK should return 401."
note "Gmail may spam-fold the first alert from @agentmail.to; mark not-spam."
pause "Signed in OK? Press Enter to finish."

finish
